function showDemand(){
	var demandHtml= '<div id="demand-content">'
		+ '        <div class="demand-content demand-wrapper">'
		+ '            <div class="demand-frame demand-relative">'
		+ '                <div class="demand-title">'
		+ '                    2015-04-10'
		+ '                </div>'
		+ '                <div class="demand-nicon">'
		+ '                    <i id="demand-nbtn"></i>'
		+ '                </div>'
		+ '                <div class="demand-notice">'
		+ '                    <div class="ntitle" id="demand-ntitle">'
		+ '                    【内测】平台2.1版本正式内测----表单报名以及全新平台架构'
		+ '                    </div>'
		+ '                    <div class="demand-ncontent" style="display:block">'
		+ '                        <p id="demand-paragraph">'
		+ '        MAKA.im对2.1平台进行全新改版，采用全新angular技术架构，在保证速度与稳定性的情况下，优化与其他webkit浏览器（遨游、360、猎豹）的兼容程度。'
		+ '        <br></br>'
		+ '        <br></br>'
		+ '      重大功能更新：'
		+ '      <br></br>'
		+ '      # MAKA 2.1平台内测版推出表单报名系统，实现手机报名与后台参会者信息管理；'
		+ '        <br></br>'
		+ '      # 实现撤销功能：可无限撤销上一步的错误操作；'
		+ '        <br></br>'
		+ '      # 增加更多页面模板：封面、单图文、多图文等；'
		+ '        <br></br>'
		+ '      # 新增固定编辑与自由编辑模式：固定模式下，您可替换页面内的图片与文字，但无法移动元素位置。'
		+ '        <br></br>'
		+ '        <br></br>'
		+ '      MAKA将在2.1平台内测结束后正式上线新版平台，内测期间，欢迎您随时反馈您对2.1平台的意见和问题… '
		+ '        <br></br>   '
		+ '      MAKA官方交流Q群：277637610'
		+ '        <br></br>'
		+ '        <br></br>   '
		+ '      2015年4月10日'
		+ '        <br></br>   '
		+ '      MAKA.im团队'
		+ '        </div>'
		+ '    </div>';
	$('#common-content').html(demandHtml);
}